package com.alchitry.labs.hardware.pinout;

public class AlchitryCuPinConverter extends PinConverter {

	@Override
	public String getFPGAPin(String pin) {
		switch (pin) {
		case "A2":
			return "M1";
		case "A3":
			return "L1";
		case "A5":
			return "J1";
		case "A6":
			return "J3";
		case "A8":
			return "G1";
		case "A9":
			return "G3";
		case "A11":
			return "E1";
		case "A12":
			return "D1";
		case "A14":
			return "C1";
		case "A15":
			return "B1";
		case "A17":
			return "D3";
		case "A18":
			return "C3";
		case "A20":
			return "A1";
		case "A21":
			return "A2";
		case "A23":
			return "A3";
		case "A24":
			return "A4";
		case "A27":
			return "A5";
		case "A28":
			return "C5";
		case "A30":
			return "D5";
		case "A31":
			return "C4";
		case "A33":
			return "D4";
		case "A34":
			return "E4";
		case "A36":
			return "F4";
		case "A37":
			return "F3";
		case "A39":
			return "H4";
		case "A40":
			return "G4";
		case "A42":
			return "H1";
		case "A43":
			return "H3";
		case "A45":
			return "K3";
		case "A46":
			return "K4";
		case "A48":
			return "N1";
		case "A49":
			return "P1";

		case "B2":
			return "A6";
		case "B3":
			return "A7";
		case "B5":
			return "A10";
		case "B6":
			return "A11";
		case "B8":
			return "C9";
		case "B9":
			return "C10";
		case "B11":
			return "A12";
		case "B12":
			return "B14";
		case "B14":
			return "C14";
		case "B15":
			return "D14";
		case "B17":
			return "E14";
		case "B18":
			return "E12";
		case "B20":
			return "F14";
		case "B21":
			return "G14";
		case "B23":
			return "H12";
		case "B24":
			return "J12";
		case "B27":
			return "H11";
		case "B28":
			return "G11";
		case "B30":
			return "G12";
		case "B31":
			return "F12";
		case "B33":
			return "F11";
		case "B34":
			return "E11";
		case "B36":
			return "D12";
		case "B37":
			return "D11";
		case "B39":
			return "C12";
		case "B40":
			return "C11";
		case "B42":
			return "D10";
		case "B43":
			return "D9";
		case "B45":
			return "D7";
		case "B46":
			return "D6";
		case "B48":
			return "C7";
		case "B49":
			return "C6";

		case "C2":
			return "M3";
		case "C3":
			return "M4";
		case "C5":
			return "L4";
		case "C6":
			return "L5";
		case "C8":
			return "M6";
		case "C9":
			return "M7";
		case "C11":
			return "L9";
		case "C12":
			return null;
		case "C14":
			return null;
		case "C15":
			return null;
		case "C17":
			return null;
		case "C18":
			return null;
		case "C20":
			return null;
		case "C21":
			return null;
		case "C23":
			return null;
		case "C24":
			return null;
		case "C27":
			return null;
		case "C28":
			return null;
		case "C30":
			return null;
		case "C31":
			return null;
		case "C33":
			return null;
		case "C34":
			return null;
		case "C36":
			return null;
		case "C37":
			return null;
		case "C39":
			return "P10";
		case "C40":
			return "P9";
		case "C42":
			return "L8";
		case "C43":
			return "L6";
		case "C45":
			return "P5";
		case "C46":
			return "P4";
		case "C48":
			return "P3";
		case "C49":
			return "P2";

		case "LED0":
			return "J11";
		case "LED1":
			return "K11";
		case "LED2":
			return "K12";
		case "LED3":
			return "K14";
		case "LED4":
			return "L12";
		case "LED5":
			return "L14";
		case "LED6":
			return "M12";
		case "LED7":
			return "N14";

		case "RESET":
			return "P8";
		case "CLOCK":
			return "P7";

		case "USB_RX":
			return "M9";
		case "USB_TX":
			return "P14";

		case "SPI_MOSI":
			return "M11";
		case "SPI_MISO":
			return "P11";
		case "SPI_SCK":
			return "P12";
		case "SPI_SS":
			return "P13";
		}
		return null;
	}

}
