package com.alchitry.labs.hardware.pinout;

public class AlchitryAuPinConverter extends PinConverter {

	@Override
	public String getFPGAPin(String pin) {
		switch (pin) {
		case "A2":
			return "N2";
		case "A3":
			return "N3";
		case "A5":
			return "M1";
		case "A6":
			return "M2";
		case "A8":
			return "P1";
		case "A9":
			return "N1";
		case "A11":
			return "L2";
		case "A12":
			return "L3";
		case "A14":
			return "J1";
		case "A15":
			return "K1";
		case "A17":
			return "H1";
		case "A18":
			return "H2";
		case "A20":
			return "G1";
		case "A21":
			return "G2";
		case "A23":
			return "K5";
		case "A24":
			return "E6";
		case "A27":
			return "P5";
		case "A28":
			return "L5";
		case "A30":
			return "H5";
		case "A31":
			return "H4";
		case "A33":
			return "J3";
		case "A34":
			return "H3";
		case "A36":
			return "J5";
		case "A37":
			return "J4";
		case "A39":
			return "K3";
		case "A40":
			return "K2";
		case "A42":
			return "L4";
		case "A43":
			return "M4";
		case "A45":
			return "M5";
		case "A46":
			return "N4";
		case "A48":
			return "P4";
		case "A49":
			return "P3";

		case "B2":
			return "D1";
		case "B3":
			return "E2";
		case "B5":
			return "A2";
		case "B6":
			return "B2";
		case "B8":
			return "E1";
		case "B9":
			return "F2";
		case "B11":
			return "F3";
		case "B12":
			return "F4";
		case "B14":
			return "A3";
		case "B15":
			return "B4";
		case "B17":
			return "A4";
		case "B18":
			return "A5";
		case "B20":
			return "B5";
		case "B21":
			return "B6";
		case "B23":
			return "A7";
		case "B24":
			return "B7";
		case "B27":
			return "C7";
		case "B28":
			return "C6";
		case "B30":
			return "D6";
		case "B31":
			return "D5";
		case "B33":
			return "F5";
		case "B34":
			return "E5";
		case "B36":
			return "G5";
		case "B37":
			return "G4";
		case "B39":
			return "D4";
		case "B40":
			return "C4";
		case "B42":
			return "E3";
		case "B43":
			return "D3";
		case "B45":
			return "C3";
		case "B46":
			return "C2";
		case "B48":
			return "C1";
		case "B49":
			return "B1";

		case "C2":
			return "T2";
		case "C3":
			return "R3";
		case "C5":
			return "T5";
		case "C6":
			return "R5";
		case "C8":
			return "N6";
		case "C9":
			return "M6";
		case "C11":
			return "R8";
		case "C12":
			return "P8";
		case "C14":
			return "P9";
		case "C15":
			return "N9";
		case "C17":
			return "P11";
		case "C18":
			return "P10";
		case "C20":
			return "N12";
		case "C21":
			return "N11";
		case "C23":
			return "P13";
		case "C24":
			return "N13";
		case "C27":
			return "R13";
		case "C28":
			return "T13";
		case "C30":
			return "R12";
		case "C31":
			return "T12";
		case "C33":
			return "R10";
		case "C34":
			return "R11";
		case "C36":
			return "T9";
		case "C37":
			return "T10";
		case "C39":
			return "T7";
		case "C40":
			return "T8";
		case "C42":
			return "R6";
		case "C43":
			return "R7";
		case "C45":
			return "T4";
		case "C46":
			return "T3";
		case "C48":
			return "R2";
		case "C49":
			return "R1";
			
		case "D8":
			return "R16";
		case "D9":
			return "R15";
		case "D11":
			return "P14";
		case "D12":
			return "M15";
		case "D42":
			return "T14";
		case "D43":
			return "T15";

		case "LED0":
			return "K13";
		case "LED1":
			return "K12";
		case "LED2":
			return "L14";
		case "LED3":
			return "L13";
		case "LED4":
			return "M16";
		case "LED5":
			return "M14";
		case "LED6":
			return "M12";
		case "LED7":
			return "N16";

		case "RESET":
			return "P6";
		case "CLOCK":
			return "N14";

		case "USB_RX":
			return "P16";
		case "USB_TX":
			return "P15";

		case "SPI_D0":
			return "J13";
		case "SPI_D1":
			return "J14";
		case "SPI_D2":
			return "K15";
		case "SPI_D3":
			return "K16";
		case "SPI_SCK":
			return "E8";
		case "SPI_SS":
			return "L12";
		}
		return null;
	}

}
