/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.1-20210625075833+0000/samples
 */
import org.gradle.internal.os.OperatingSystem

plugins {
    kotlin("jvm") version "1.5.21"
    application
}

val main = "MainKt"

application {
    mainClass.set(main)
    applicationDefaultJvmArgs = listOf("-XstartOnFirstThread")  // required by SWT
}

tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = main
    }
    duplicatesStrategy = DuplicatesStrategy.WARN
    from(configurations.compileClasspath.map { config -> config.map { if (it.isDirectory) it else zipTree(it) } })
}

repositories {
    mavenCentral()
    maven(url = "https://maven-eclipse.github.io/maven")  // for SWT
}

dependencies {
    implementation("org.apache.commons:commons-compress:1.21")
}

sourceSets.main {
    java.srcDirs("src")
    resources.srcDirs("res")

    dependencies {
        implementation("org.jetbrains.kotlin:kotlin-stdlib:1.5.21")
        implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.1")
        implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.5.1")
        implementation("commons-io:commons-io:2.11.0")
        implementation("org.apache.commons:commons-text:1.9")
        implementation("org.antlr:antlr4-runtime:4.8")  // stay 4.8 to disable compilation warnings.
        implementation("org.jdom:jdom2:2.0.6")
        implementation("org.usb4java:usb4java:1.3.0")
        implementation("com.fazecast:jSerialComm:2.7.0")
        implementation("de.brudaswen.kotlinx.coroutines:kotlinx-coroutines-swt:1.0.0")
        when (OperatingSystem.current()) {
            OperatingSystem.MAC_OS -> implementation("org.eclipse.swt:org.eclipse.swt.cocoa.macosx.x86_64:4.6")
            OperatingSystem.LINUX -> implementation("org.eclipse.swt:org.eclipse.swt.gtk.linux.x86_64:4.6")
            OperatingSystem.WINDOWS -> implementation("org.eclipse.swt:org.eclipse.swt.win32.win32.x86_64:4.6")
        }
        implementation(files("lib/yad2xxJava-1.0.jar"))
    }
}
