package com.alchitry.labs.hardware.usb.ftdi.enums;

public enum CbusxFunc {
	CBUSX_TRISTATE, CBUSX_TXLED, CBUSX_RXLED, CBUSX_TXRXLED, CBUSX_PWREN, CBUSX_SLEEP, CBUSX_DRIVE_0, CBUSX_DRIVE1, CBUSX_IOMODE, CBUSX_TXDEN, CBUSX_CLK24, CBUSX_CLK12, CBUSX_CLK6, CBUSX_BAT_DETECT, CBUSX_BAT_DETECT_NEG, CBUSX_I2C_TXE, CBUSX_I2C_RXF, CBUSX_VBUS_SENSE, CBUSX_BB_WR, CBUSX_BB_RD, CBUSX_TIME_STAMP, CBUSX_AWAKE;
}
