package com.alchitry.labs.hardware.ftdi.enums;

public enum CbusFunc {
	CBUS_TXDEN, CBUS_PWREN, CBUS_RXLED, CBUS_TXLED, CBUS_TXRXLED, CBUS_SLEEP, CBUS_CLK48, CBUS_CLK24, CBUS_CLK12, CBUS_CLK6, CBUS_IOMODE, CBUS_BB_WR, CBUS_BB_RD;
}
