package com.alchitry.labs.parsers.lucid.toVerilog;

import com.alchitry.labs.gui.main.MainWindow;

public class LucidConvertedHeader {
	private LucidConvertedHeader(){}
	
	public static final String header = "/*\n"
			+ "   This file was generated automatically by the Mojo IDE version "+MainWindow.VERSION+".\n"
			+ "   Do not edit this file directly. Instead edit the original Lucid source.\n"
			+ "   This is a temporary file and any changes made to it will be destroyed.\n"
			+ "*/\n";
}
